# Generated by Django 2.2.7 on 2020-01-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore', '0003_auto_20200124_0721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
