# Generated by Django 2.2.7 on 2020-01-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore', '0004_delete_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
